export const LIGA_ARGENTINA  = [
    {    nombre: "Boca Juniors",img:"/public/escudos/ligaArgentina/boca.png"},
    {   nombre: "River Plate",img:"/public/escudos/ligaArgentina/river.png"},
    {   nombre: "Racing",img:"/public/escudos/ligaArgentina/racing.png"},
    {   nombre: "Independiente",img:"/public/escudos/ligaArgentina/independiente.png"},
    {   nombre: "San Lorenzo",img:"/public/escudos/ligaArgentina/san-lorenzo.png"},
    {  nombre: "Velez Sarsfield",img:"/public/escudos/ligaArgentina/velez.png"},
    {  nombre: "Union de Santa Fe",img:"/public/escudos/ligaArgentina/union.png"},
    {  nombre: "Tigre",img:"/public/escudos/ligaArgentina/tigre.png"},
    {  nombre: "Talleres",img:"/public/escudos/ligaArgentina/talleres.png"},
    {  nombre: "Sarmiento de junin",img:"/public/escudos/ligaArgentina/sarmiento-de-junin.png"},
    { nombre: "Rosario central",img:"/public/escudos/ligaArgentina/rosario-central.png"},
    { nombre: "Riestra",img:"/public/escudos/ligaArgentina/riestra.png"},
    { nombre: "Platense", img:"/public/escudos/ligaArgentina/platense.png"},
    { nombre: "Newells Old Boys",img:"/public/escudos/ligaArgentina/newells.png"},
    { nombre:"Lanus", img:"/public/escudos/ligaArgentina/lanus.png" },
    { nombre:"Instituto", img:"/public/escudos/ligaArgentina/instituto.png" },
    { nombre:"independiente Rivadavia", img:"/public/escudos/ligaArgentina/independiente-rivadavia.png" },
    { nombre:"Huracan", img:"/public/escudos/ligaArgentina/huracan.png" },
    { nombre:"Gimnasia y Esgrima de La Plata", img:"/public/escudos/ligaArgentina/gimnasia-de-la-plata.png" },
    { nombre:"Gimnasia y Esgrima de Mendoza", img:"/public/escudos/ligaArgentina/gimnasia_de_mendoza.png" },
    { nombre:"Estudiantes de La Plata", img:"/public/escudos/ligaArgentina/estudiantes.png" },
    { nombre:"Estudiantes de Rio Cuarto", img:"/public/escudos/ligaArgentina/estudiantes-de-RC.png" },
    { nombre:"Defensa y Justicia", img:"/public/escudos/ligaArgentina/defensa_y_justicia.png" },
    { nombre:"Central Cordoba", img:"/public/escudos/ligaArgentina/central-cordoba.png" },
    { nombre:"Belgrano", img:"/public/escudos/ligaArgentina/belgrano.png" },
    { nombre:"Banfield", img:"/public/escudos/ligaArgentina/banfield.png" },
    { nombre:"atletico Tucuman", img:"/public/escudos/ligaArgentina/atletico-tucuman.png" },
    { nombre:"Argentinos Juniors", img:"/public/escudos/ligaArgentina/argentinos-juniors.png" },
    { nombre:"Aldosivi", img:"/public/escudos/ligaArgentina/aldosivi.png" },
]
export const LIGA_ESPAÑOLA = [
    {   nombre: "Barcelona",img:"/public/escudos/ligaEspaña/barcelona.png"},
    {   nombre: "Real Madrid",img:"/public/escudos/ligaEspaña/real-madrid.png"},
]