export const LIGA_ARGENTINA  = [
    {    nombre: "Boca Juniors",img:"/public/escudos/ligaArgentina/boca.png"},
    {   nombre: "River Plate",img:"/public/escudos/ligaArgentina/river.png"},
    {   nombre: "Racing",img:"/public/escudos/ligaArgentina/racing.png"},
    {   nombre: "Independiente",img:"/public/escudos/ligaArgentina/independiente.png"},
    {   nombre: "San Lorenzo",img:"/public/escudos/ligaArgentina/san-lorenzo.png"},
    {  nombre: "Velez Sarsfield",img:"/public/escudos/ligaArgentina/velez.png"},
    {  nombre: "Union de Santa Fe",img:"/public/escudos/ligaArgentina/union.png"},
    {  nombre: "Tigre",img:"/public/escudos/ligaArgentina/tigre.png"},
    {  nombre: "Talleres",img:"/public/escudos/ligaArgentina/talleres.png"},
    {  nombre: "Sarmiento de junin",img:"/public/escudos/ligaArgentina/sarmiento-de-junin.png"},
    { nombre: "Rosario central",img:"/public/escudos/ligaArgentina/rosario-central.png"},
    { nombre: "Riestra",img:"/public/escudos/ligaArgentina/riestra.png"},
    { nombre: "Platense", img:"/public/escudos/ligaArgentina/platense.png"},
    { nombre: "Newells Old Boys",img:"/public/escudos/ligaArgentina/newells.png"},
    { nombre:"Lanus", img:"/public/escudos/ligaArgentina/lanus.png" },
    { nombre:"Instituto", img:"/public/escudos/ligaArgentina/instituto.png" },
    { nombre:"independiente Rivadavia", img:"/public/escudos/ligaArgentina/independiente-rivadavia.png" },
    { nombre:"Huracan", img:"/public/escudos/ligaArgentina/huracan.png" },
    { nombre:"Gimnasia y Esgrima de La Plata", img:"/public/escudos/ligaArgentina/gimnasia-de-la-plata.png" },
    { nombre:"Gimnasia y Esgrima de Mendoza", img:"/public/escudos/ligaArgentina/gimnasia_de_mendoza.png" },
    { nombre:"Estudiantes de La Plata", img:"/public/escudos/ligaArgentina/estudiantes.png" },
    { nombre:"Estudiantes de Rio Cuarto", img:"/public/escudos/ligaArgentina/estudiantes-de-RC.png" },
    { nombre:"Defensa y Justicia", img:"/public/escudos/ligaArgentina/defensa_y_justicia.png" },
    { nombre:"Central Cordoba", img:"/public/escudos/ligaArgentina/central-cordoba.png" },
    { nombre:"Belgrano", img:"/public/escudos/ligaArgentina/belgrano.png" },
    { nombre:"Banfield", img:"/public/escudos/ligaArgentina/banfield.png" },
    { nombre:"atletico Tucuman", img:"/public/escudos/ligaArgentina/atletico-tucuman.png" },
    { nombre:"Argentinos Juniors", img:"/public/escudos/ligaArgentina/argentinos-juniors.png" },
    { nombre:"Aldosivi", img:"/public/escudos/ligaArgentina/aldosivi.png" },
]
export const LIGA_ESPAÑOLA = [
    {   nombre: "Alaves",img:"/public/escudos/ligaEspaña/alaves.png"},
    {   nombre: "Athletic de Bilbao",img:"/public/escudos/ligaEspaña/athletic_club.png"},
    {   nombre: "Barcelona",img:"/public/escudos/ligaEspaña/barcelona.png"},
    {   nombre: "Real Madrid",img:"/public/escudos/ligaEspaña/real-madrid.png"},
    {   nombre: "Atletico de Madrid",img:"/public/escudos/ligaEspaña/atletico-madrid.png"},
    {   nombre: "Celta de Vigo",img:"/public/escudos/ligaEspaña/celta_de_vigo.png"},
    {   nombre: "Sevilla",img:"/public/escudos/ligaEspaña/sevilla.png"},
    {  nombre: "Espanyol",img:"/public/escudos/ligaEspaña/espanyol.png"},
    {  nombre: "Girona",img:"/public/escudos/ligaEspaña/girona.png"},
    {  nombre: "Levante",img:"/public/escudos/ligaEspaña/levante.png"},
    {   nombre: "Real Sociedad",img:"/public/escudos/ligaEspaña/real_sociedad.png"},
    {  nombre: "Elche",img:"/public/escudos/ligaEspaña/elche.png"},
    {   nombre: "Real Betis",img:"/public/escudos/ligaEspaña/real_betis.png"},
    {  nombre: "Real Oviedo",img:"/public/escudos/ligaEspaña/real-oviedo.png"},
    {  nombre: "Rayo Vallecano",img:"/public/escudos/ligaEspaña/rayo_vallecano.png"},
    {  nombre: "Mallorca",img:"/public/escudos/ligaEspaña/mallorca.png"},
    {  nombre: "Getafe",img:"/public/escudos/ligaEspaña/getafe.png"},
    {  nombre: "Osasuna",img:"/public/escudos/ligaEspaña/osasuna.png"},
    {   nombre: "Valencia",img:"/public/escudos/ligaEspaña/valencia.png"},
    {   nombre: "Villarreal",img:"/public/escudos/ligaEspaña/villarreal.png"},
    
]

export const PREMIER_LEAGUE = [
    {   nombre: "Manchester United",img:"/public/escudos/premierLeague/manchester_united.png"},
    {   nombre: "Liverpool",img:"/public/escudos/premierLeague/liverpool.png"},
    {   nombre: "Chelsea",img:"/public/escudos/premierLeague/chelsea.png"},
    {   nombre: "Arsenal",img:"/public/escudos/premierLeague/arsenal.png"},
    {   nombre: "Manchester City",img:"/public/escudos/premierLeague/manchester-city.png"},
    {   nombre: "Tottenham Hotspur",img:"/public/escudos/premierLeague/tottenham.png"},
    {   nombre: "Everton",img:"/public/escudos/premierLeague/everton.png"},
    {   nombre: "Aston Villa",img:"/public/escudos/premierLeague/aston_villa.png"},
    {   nombre: "Leeds United",img:"/public/escudos/premierLeague/leeds.png"},
    {   nombre: "West Ham United",img:"/public/escudos/premierLeague/west-ham.png"},
    {   nombre: "Newcastle United",img:"/public/escudos/premierLeague/newcastle.png"},
    {   nombre: "Wolverhampton Wanderers",img:"/public/escudos/premierLeague/wolves.png"},
    {   nombre: "Nottingham Forest",img:"/public/escudos/premierLeague/nottingham.png"},
    {   nombre: "Bournemouth", img:"/public/escudos/premierLeague/bournemouth.png" },
    {   nombre:"Brighton Hove Albion", img:"/public/escudos/premierLeague/brighton.png" },
    {   nombre:"Crystal Palace", img:"/public/escudos/premierLeague/crystal-palace.png" },
    {   nombre:"brentford", img:"/public/escudos/premierLeague/brentford.png" },
    {   nombre:"Fulham", img:"/public/escudos/premierLeague/fulham.png" },
    {   nombre:"sunderland", img:"/public/escudos/premierLeague/sunderland.png" },
    {   nombre:"Burnley", img:"/public/escudos/premierLeague/burnley.png" },
]